# Note: I'm trying a lower learning rate for the generator
LEARNING_RATE_DISCRIMINATOR = 0.0002
LEARNING_RATE_GENERATOR = 0.00005

ADDITIONAL_FILTERS_PER_BLOCK_DISCRIMINATOR = 0
BASE_N_FILTERS_DISCRIMINATOR = 32

ADDITIONAL_FILTERS_PER_BLOCK_GENERATOR = 0
BASE_N_FILTERS_GENERATOR = 128

DROPOUT_RATE = 0.0

N_BLOCKS_DISCRIMINATOR = 4
N_BLOCKS_GENERATOR = 4

# Note: NAIP scenes have 4 bands (R B G NIR)
PATCH_SHAPE = (256, 256, 4)

NOISE_SHAPE = (256, 256, 1)

BATCH_SIZE = 8
STEPS_PER_EPOCH = 64

LABEL_SMOOTHING_ALPHA = 0.9
